### ISSUE TITLE
Описание процессингов

### ISSUE THREAD

**Issue by AlphaAnklav** [dimmpixeye/ecs#4]
Стоит дополнить описание процессингов  в README-rus.md & README.md, объяснив посылку сигнала:
"...каждый раз когда вы используете   ProcessingSignals.Default.SendSignal(new ваштипсигнала);  он отправит этот сигнал всем подписанным экземплярам с IRecieve<ваштипсигнала>"
Что-то на подобии.
P.S: мой первый Issue :D

**Comment by dimmpixeye** [comment]
И первый issue у Акторов : )) окей - принято
